{{ if or .Values.environmentVariables .Values.googleApplicationCredentials }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "replicant.name" . }}-env
  labels:
    {{- include "replicant.labels" . | nindent 4 }}
data:
  {{- with .Values.environmentVariables }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.googleApplicationCredentials }}
  GOOGLE_APPLICATION_CREDENTIALS: "/secrets/key.json"
  {{- end }}
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "replicant.name" . }}-config
  labels:
    {{- include "replicant.labels" . | nindent 4 }}
data:
  replicant.yaml: |
     {{- toYaml .Values.config | nindent 4 }}
