{{ if .Values.secretEnvironmentVariables }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "replicant.name" . }}-secret-env
  labels:
    {{- include "replicant.labels" . | nindent 4 }}
type: Opaque
data:
  {{ range $k,$v := .Values.secretEnvironmentVariables }}
  {{- $k }}: {{ $v | b64enc }}
  {{ end }}
{{ end }}
{{ if .Values.googleApplicationCredentials }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "replicant.name" . }}-gcp-sa
  labels:
    {{- include "replicant.labels" . | nindent 4 }}
type: Opaque
data:
  key.json: {{ .Values.googleApplicationCredentials | b64enc }}
{{ end }}
