{{- if .Values.serviceAccount.create -}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "replicant.serviceAccountName" . }}
  labels:
    {{- include "replicant.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
